version: 2

build:
  os: ubuntu-20.04
  tools: {python: "3.8"}
  jobs:
    post_install:
      - pip install poetry==1.2.1
      - poetry config virtualenvs.create false
      - poetry install --with docs