{% set name = "scikit-rf" %}
{% set version = "0.19.0" %}
{% set hash_val = "8223204281599ba14b685d7e28b7e361" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python>=3.6
    - setuptools
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib
    - openpyxl

    
  run:
    - python>=3.6
    - setuptools
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib
    - xlwt
    - xlrd
    - networkx
    - openpyxl
    

test:
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD-3-Clause
  summary: 'Object Oriented Microwave Engineering'
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf
  
extra:
  recipe-maintainers:
    - arsenovic
